config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  get "dashboard", to: "dashboard#index"

  resources :boards, only: [ :new, :create, :show, :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
  include Pundit::Authorization
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    authorize board
  end

  def edit
    authorize board
  end

  def update
    authorize board

    if board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize board
    board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @boards = Board.order(created_at: :asc)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boards/_form.html.erb
<%= form_with model: board, local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="space-y-8 divide-y divide-gray-200">
        <div class="pt-8">
            <div>
                <% if board.new_record? %>
                    <h3 class="text-lg font-medium leading-6 text-gray-900">New Board</h3>
                    <p class="mt-1 text-sm text-gray-500">This form creates a new board.</p>
                <% else %>
                    <h3 class="text-lg font-medium leading-6 text-gray-900">Edit Board</h3>
                    <p class="mt-1 text-sm text-gray-500">This form edits a new board.</p>
                <% end %>
            </div>
            <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
                <div class="sm:col-span-6">
                    <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
                    <div class="mt-1 flex items-center rounded-md bg-white pl-3 outline-1 -outline-offset-1 outline-gray-300 focus-within:outline-2 focus-within:-outline-offset-2 focus-within:outline-indigo-600">
                        <%= f.text_field :name, class: "block min-w-0 grow py-1.5 pr-3 pl-1 text-base text-gray-900 placeholder:text-gray-400 focus:outline-none sm:text-sm/6" %>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
        <%= link_to "Cancel", root_path, class: "text-sm/6 font-semibold text-gray-900" %>
        <%= f.submit "Create Board", class: "cursor-pointer rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
    </form>
<% end %>

app/views/boards/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-3xl">
        <%= render "form", board: @board %>
    </div>
</div>

app/views/boards/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-3xl">
        <%= render "form", board: @board %>
    </div>
</div>

app/views/boards/show.html.erb
<p>Hello from BoardsCotroller#show</p>

app/views/dashboard/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
    <div class="mx-auto max-w-4xl">
        <ul role=list class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <% @boards.each do |board| %>
                <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
                    <div class="flex w-full items-center justify-between p-6 space-x-6">
                        <div class="flex-1 truncate">
                            <div class="flex items-center space-x-3">
                                <h3 class="truncate text-sm front-medium text-gray-900"><%= link_to board.name, board_path(board), class: "link" %></h3>
                            </div>
                            <p class="mt-1 truncate text-sm text-gray-500">Some text here</p>
                        </div>
                    </div>
                    <div>
                        <div class="-mt-px flex divide-x divide-gray-200">
                            <div class="flex w-0 flex-1">
                                <%= link_to edit_board_path(board), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                                    <span class="ml-3">Edit</span>
                                <% end %>
                            </div>
                            <div class="-ml-px flex w-0 flex-1">
                                <%= link_to board_path(board), data: { "turbo-method": :delete }, class: "relative inline-flex w-0 flex-1 items-center justify-center rounded-br-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                                    <span class="ml-3 text-red-700">Delete</span>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/home/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-3xl">
        Hello from Homecontroller#index
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="bg-white border-gray-200">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to root_path do %>
        <%= image_tag "trello_logo.png", class: "h-8" %>
    <% end %>
    <% if user_signed_in? %>
    <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        <%= link_to new_board_path do %>
            <button type="button" class="cursor-pointer text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">+ New Board</button>
        <% end %>
        <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class:"link text-sm px-5 py-2 text-center" %>
        <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
            </svg>
        </button>
    </div>
    <%# <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
        <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0">
            <li>
                <a href="#" class="link text-sm py-2 px-3 md:p-0" aria-current="page">Dashboard</a>
            </li>
        </ul>
    </div> %>
    <% else %>
    <div class="flex items-center space-x-6 rtl:space-x-reverse">
        <%= link_to "Register", new_user_registration_path, class: "text-sm link" %>
        <%= link_to "Login", new_user_session_path, class: "text-sm link" %>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Trello Clone" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <%= render "layouts/navbar" %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>